version: '3'

services:

  ci-frontend:
    image: ci-frontend
    build:
      context: ./CloudImage-frontend
    container_name: ci-frontend
    ports:
      - "80:80"
    expose:
      - 80
    networks:
      - ci-network 
    depends_on:
      - ci-backend
    environment:      
      BACKEND_URL: 'http://ci-backend:5246'

  ci-backend:
    image: ci-backend
    build: 
      context: ./CloudImage-backend/CloudImage
    container_name: ci-backend
    ports:
      - "5246:5246"
    networks:
      - ci-network
  
  ci-db:
    container_name: ci-db
    image: postgres:latest
    restart: always
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=root
      - POSTGRES_DB=CloudImage
    ports:
      - "5443:5432"
    expose:
      - 5433
      - 5432
    volumes:
      - app_data:/var/lib/postgresql/data
    networks:
      - ci-network

volumes:
  app_data:

networks:
  ci-network:
    driver: bridge

    